name: Build and Test

on:
  push:
    branches:
      - master  # or your default branch name
  pull_request:
    branches:
      - master  # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install bun
    - name: Install bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    # Install dependencies with bun
    - name: Install dependencies
      run: bun install

    # Run build with bun
    - name: Run build
      run: bun run build
